apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmao-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmao-backend
  template:
    metadata:
      labels:
        app: gmao-backend
    spec:
      initContainers:
      - name: prisma-migrate
        image: ghcr.io/youssefag1337/gmao-backend:c19e6d35b26715f0ab08ada204f378449a3a8629
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: 
          - npx prisma migrate deploy && npm run db:seed
        envFrom:
        - secretRef:
            name: gmao-secret
      containers:
      - name: gmao-backend
        image: ghcr.io/youssefag1337/gmao-backend:c19e6d35b26715f0ab08ada204f378449a3a8629
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: gmao-secret
        env:
        - name: PORT
          value: "8080"
        # We can simulate FRONTEND_URL if needed, though for local we can just use the ingress host
        - name: FRONTEND_URL
          value: "http://localhost"
