apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmao-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmao-frontend
  template:
    metadata:
      labels:
        app: gmao-frontend
    spec:
      containers:
      - name: gmao-frontend
        image: ghcr.io/youssefag1337/gmao-frontend:c19e6d35b26715f0ab08ada204f378449a3a8629
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
