apiVersion: v1
kind: Secret
metadata:
  name: gmao-secret
  namespace: default
type: Opaque
stringData:
  # Using the mysql-service DNS name in Kubernetes
  DATABASE_URL: "mysql://root:rootpassword@mysql-service:3306/gmao"
  JWT_SECRET: "super-secret-jwt-key-for-local-dev-only"
  JWT_EXPIRES_IN: "1d"
  JWT_REFRESH_SECRET: "super-secret-refresh-key-for-local-dev-only"
  JWT_REFRESH_EXPIRES_IN: "7d"
