apiVersion: v1
kind: Secret
metadata:
  name: gmao-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "mysql://root:rootpassword@mysql-service:3306/gmao"
  ACCESS_TOKEN_SECRET: "super-secret-jwt-key-for-local-dev-only"
  ACCESS_TOKEN_EXPIRY: "1d"
  REFRESH_TOKEN_SECRET: "super-secret-refresh-key-for-local-dev-only"
  REFRESH_TOKEN_EXPIRY: "7d"
