apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: aegis-project
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.1
    helm:
      values: |
        grafana:
          adminPassword: "thales-admin"
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.local
          # Optional: Pre-configure some default data sources or dashboards if needed
        prometheus:
          prometheusSpec:
            # Allow discovering ServiceMonitors across all namespaces without label matching
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
